#!/bin/bash

# Execute with each .profile load to add all
# directories (general, push, etc.) in $1 to the path.
# Note: Only directories one deep will be added.

# Run in .profile with: source [dir]/add_to_path [dir]

for d in $1/*/ ; do
    [ -L "${d%/}" ] && continue
    export PATH=$PATH:$d
done