#!/bin/bash

# Shutdown (w/tuto) after passed command finishes.
# Note: must be run w/sudo.

# Check if the script has sudo privileges
if [[ ! $EUID -eq 0 ]]; then
  echo "Run with sudo."
  exit 1
fi

"$@" && tuto || tuto